module.exports = {
  CONFIG_FILE: 'config.json',
  INPUT_FILES_DIR: 'in/tables',
  OUTPUT_FILES_DIR: 'out/tables',
  EXIT_STATUS_SUCCESS: 0,
  EXIT_STATUS_FAILURE: 1,
  ANALYSE_SYNTAX_DEFAULT: true,
  ANALYSE_ENTITIES_DEFAULT: true,
  ANALYSE_SENTIMENT_DEFAULT: true,
  ANALYSE_CUSTOM_TEXT_DEFAULT: false
}